language: ruby
rvm:
  - 2.0.0-p247
script:
  - RAILS_ENV=test bundle exec rake db:setup db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

before_script:
  - bundle exec rake travis:spinup
  - bundle exec rake travis:setup
